"""timeimportant

Revision ID: 1b1b261c46ec
Revises: a25397fef87b
Create Date: 2021-04-03 03:38:40.414105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b1b261c46ec'
down_revision = 'a25397fef87b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_product_timestamp'), 'product', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_timestamp'), table_name='product')
    op.drop_column('product', 'timestamp')
    # ### end Alembic commands ###
