"""newclass

Revision ID: 3a2e7975077f
Revises: 1b1b261c46ec
Create Date: 2021-04-14 02:02:29.538037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a2e7975077f'
down_revision = '1b1b261c46ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passbook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('product', sa.Integer(), nullable=True),
    sa.Column('credit', sa.Float(), nullable=True),
    sa.Column('debit', sa.Float(), nullable=True),
    sa.Column('current_amount', sa.Float(), nullable=True),
    sa.Column('bid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bid'], ['bid.id'], ),
    sa.ForeignKeyConstraint(['product'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passbook')
    # ### end Alembic commands ###
